### ISSUE TITLE
Hooks should be installed using WebhooksManager

### ISSUE THREAD

**Issue by icefox** [Shopify/shopify-fulfillment-integration#5]
As this is cited as example code for teaching new developers this should use the built in ShopifyApp::WebhooksManager rather than directly calling Webhook.new().  It is much too easy for developers to go off and roll there own hook solution that isn't as good as WebhooksManager if they don't know it exists, potentially building something that causes problems down the road when their home grown hook doesn't use a queue and times out.

Edit: I would make a patch that changes it to use WebhooksManager, but I am not entirely sure the correct way to do that (my current project is just more copy/paste of more web hooks from the example, but I recognize that it is bad and should be changed) so I have made a pull request to at least mention it so others will be aware of it earlier when just reading over the code.

Edit2: Along the same lines I am not sure if I have done something wrong, but the install is never called so I now just call it explicitly inside of '/', was the install/uninstall deprecated a while back in favor of something like WebhooksManager?

**Comment by kevinhughes27** [comment]
Couple of things - see my comment in #6 about the intention of this repo.

While it might be possible to pull in the WebhooksManager class from ShopifyApp its currently not a dependency here and per my comment in #6 its not really the intent of this repo.

For your issue with the install method not being called I believe this is on an old version of shopify-sinatra-app. The method is now called `after_auth`
